server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #保证拿到的是ip而不是host

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

